services:
  - type: web
    name: ai-dream-catcher-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRODUCT_ID
        sync: false
      - key: STRIPE_PRICE_ID_MONTHLY
        sync: false
      - key: STRIPE_PRICE_ID_YEARLY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: ai-dream-catcher-db
    plan: starter
